# frontend/src/utils/career_profiles.py
from typing import Dict, List, Any

CAREER_PROFILES: List[Dict[str, Any]] = [
    # --- SOFTWARE ENGINEERING & WEB ---
    {
        "id": "backend_dev",
        "title": "Backend Developer",
        "skill_weights": {"Python": 0.25, "DBMS": 0.20, "Data Structures": 0.15, "Algorithms": 0.15, "OOP": 0.15, "Flask": 0.10},
        "personality_target": {"openness": 3, "conscientiousness": 4, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "frontend_dev",
        "title": "Frontend Developer",
        "skill_weights": {"Javascript": 0.40, "React": 0.20, "CSS/HTML": 0.15, "UI/UX Design": 0.10, "Data Structures": 0.05, "Browser APIs": 0.10},
        "personality_target": {"openness": 4, "conscientiousness": 3, "extraversion": 3, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "fullstack_dev",
        "title": "Fullstack Developer",
        "skill_weights": {"Javascript": 0.25, "Python": 0.20, "DBMS": 0.15, "React": 0.15, "Node.js": 0.15, "Cloud Basics": 0.10},
        "personality_target": {"openness": 4, "conscientiousness": 4, "extraversion": 3, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "ios_developer",
        "title": "iOS Developer",
        "skill_weights": {"Swift": 0.45, "SwiftUI": 0.20, "Algorithms": 0.10, "Design Patterns": 0.15, "Mobile Security": 0.10},
        "personality_target": {"openness": 4, "conscientiousness": 4, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "android_developer",
        "title": "Android Developer",
        "skill_weights": {"Kotlin": 0.45, "Java": 0.15, "Android SDK": 0.20, "Algorithms": 0.10, "DBMS": 0.10},
        "personality_target": {"openness": 4, "conscientiousness": 4, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "systems_programmer",
        "title": "Systems Programmer",
        "skill_weights": {"C/C++": 0.40, "Operating Systems": 0.25, "Memory Management": 0.15, "Algorithms": 0.10, "Data Structures": 0.10},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 1, "agreeableness": 2, "neuroticism": 3},
    },
    {
        "id": "ruby_dev",
        "title": "Ruby on Rails Developer",
        "skill_weights": {"Ruby": 0.40, "Rails": 0.30, "DBMS": 0.15, "Javascript": 0.10, "Testing": 0.05},
        "personality_target": {"openness": 4, "conscientiousness": 3, "extraversion": 3, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "golang_dev",
        "title": "Go Developer",
        "skill_weights": {"Go": 0.45, "Concurrency": 0.20, "Microservices": 0.15, "Docker": 0.10, "Algorithms": 0.10},
        "personality_target": {"openness": 3, "conscientiousness": 4, "extraversion": 2, "agreeableness": 3, "neuroticism": 1},
    },
    {
        "id": "java_enterprise_dev",
        "title": "Java Enterprise Developer",
        "skill_weights": {"Java": 0.35, "Spring Boot": 0.25, "DBMS": 0.20, "Microservices": 0.10, "OOP": 0.10},
        "personality_target": {"openness": 2, "conscientiousness": 5, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "php_laravel_dev",
        "title": "PHP/Laravel Developer",
        "skill_weights": {"PHP": 0.40, "Laravel": 0.30, "MySQL": 0.15, "Javascript": 0.10, "HTML/CSS": 0.05},
        "personality_target": {"openness": 3, "conscientiousness": 4, "extraversion": 3, "agreeableness": 4, "neuroticism": 2},
    },

    # --- DATA SCIENCE & AI ---
    {
        "id": "data_analyst",
        "title": "Data Analyst",
        "skill_weights": {"Pandas": 0.30, "Numpy": 0.25, "Python": 0.20, "DBMS": 0.15, "Statistics": 0.10},
        "personality_target": {"openness": 4, "conscientiousness": 4, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "ml_engineer",
        "title": "Machine Learning Engineer",
        "skill_weights": {"Python": 0.20, "PyTorch": 0.20, "Linear Algebra": 0.20, "Algorithms": 0.20, "Data Structures": 0.10, "Numpy": 0.10},
        "personality_target": {"openness": 4, "conscientiousness": 3, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "data_scientist",
        "title": "Data Scientist",
        "skill_weights": {"Python": 0.20, "Statistics": 0.25, "ML Theory": 0.20, "Communication": 0.15, "Pandas": 0.20},
        "personality_target": {"openness": 5, "conscientiousness": 3, "extraversion": 3, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "nlp_engineer",
        "title": "NLP Engineer",
        "skill_weights": {"Transformers": 0.30, "Python": 0.20, "Linguistics": 0.15, "PyTorch": 0.25, "Algorithms": 0.10},
        "personality_target": {"openness": 5, "conscientiousness": 3, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "cv_engineer",
        "title": "Computer Vision Engineer",
        "skill_weights": {"OpenCV": 0.30, "PyTorch": 0.25, "C++": 0.15, "Linear Algebra": 0.20, "Python": 0.10},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "data_engineer",
        "title": "Data Engineer",
        "skill_weights": {"SQL": 0.30, "Spark": 0.25, "Python": 0.15, "ETL Pipelines": 0.20, "Cloud Data": 0.10},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "ai_researcher",
        "title": "AI Researcher",
        "skill_weights": {"Mathematics": 0.40, "Python": 0.15, "Research Writing": 0.15, "DL Theory": 0.30},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 1, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "mlops_engineer",
        "title": "MLOps Engineer",
        "skill_weights": {"Docker": 0.20, "Kubernetes": 0.20, "Python": 0.20, "Model Monitoring": 0.20, "CI/CD": 0.20},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "bi_developer",
        "title": "Business Intelligence Developer",
        "skill_weights": {"SQL": 0.35, "Tableau/PowerBI": 0.35, "Data Modeling": 0.20, "Communication": 0.10},
        "personality_target": {"openness": 3, "conscientiousness": 4, "extraversion": 4, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "quantitative_analyst",
        "title": "Quantitative Analyst",
        "skill_weights": {"Stochastic Calculus": 0.30, "C++": 0.25, "Python": 0.20, "Finance Theory": 0.25},
        "personality_target": {"openness": 4, "conscientiousness": 5, "extraversion": 2, "agreeableness": 2, "neuroticism": 4},
    },

    # --- CYBERSECURITY ---
    {
        "id": "pentester",
        "title": "Penetration Tester",
        "skill_weights": {"Network Security": 0.30, "Scripting": 0.20, "Exploit Dev": 0.25, "OS Internals": 0.15, "Reporting": 0.10},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 2, "agreeableness": 2, "neuroticism": 3},
    },
    {
        "id": "soc_analyst",
        "title": "SOC Analyst",
        "skill_weights": {"SIEM Tools": 0.35, "Network Traffic": 0.25, "Incident Response": 0.20, "Log Analysis": 0.20},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 2, "agreeableness": 3, "neuroticism": 4},
    },
    {
        "id": "security_architect",
        "title": "Security Architect",
        "skill_weights": {"Network Design": 0.30, "Cryptography": 0.20, "Cloud Security": 0.30, "Compliance": 0.20},
        "personality_target": {"openness": 4, "conscientiousness": 5, "extraversion": 3, "agreeableness": 3, "neuroticism": 1},
    },
    {
        "id": "malware_analyst",
        "title": "Malware Analyst",
        "skill_weights": {"Reverse Engineering": 0.40, "Assembly": 0.30, "C/C++": 0.15, "OS Internals": 0.15},
        "personality_target": {"openness": 4, "conscientiousness": 5, "extraversion": 1, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "cryptographer",
        "title": "Cryptographer",
        "skill_weights": {"Number Theory": 0.45, "C/C++": 0.15, "Python": 0.15, "Algorithm Design": 0.25},
        "personality_target": {"openness": 5, "conscientiousness": 5, "extraversion": 1, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "appsec_engineer",
        "title": "Application Security Engineer",
        "skill_weights": {"Secure Coding": 0.35, "Code Audit": 0.25, "CI/CD Security": 0.20, "OWASP": 0.20},
        "personality_target": {"openness": 4, "conscientiousness": 5, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "forensic_investigator",
        "title": "Digital Forensics Investigator",
        "skill_weights": {"Chain of Custody": 0.20, "File Systems": 0.30, "Legal Procedures": 0.20, "Memory Forensics": 0.30},
        "personality_target": {"openness": 2, "conscientiousness": 5, "extraversion": 2, "agreeableness": 3, "neuroticism": 3},
    },
    {
        "id": "grc_specialist",
        "title": "GRC Specialist",
        "skill_weights": {"Risk Assessment": 0.40, "Compliance Frameworks": 0.30, "Audit": 0.20, "Communication": 0.10},
        "personality_target": {"openness": 2, "conscientiousness": 5, "extraversion": 4, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "cloud_security_eng",
        "title": "Cloud Security Engineer",
        "skill_weights": {"IAM": 0.30, "Cloud Networking": 0.25, "Terraform": 0.20, "Security Groups": 0.25},
        "personality_target": {"openness": 4, "conscientiousness": 5, "extraversion": 2, "agreeableness": 3, "neuroticism": 1},
    },
    {
        "id": "threat_hunter",
        "title": "Threat Hunter",
        "skill_weights": {"Data Analysis": 0.30, "Security Research": 0.30, "Query Languages": 0.20, "MITRE ATT&CK": 0.20},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 2, "agreeableness": 3, "neuroticism": 3},
    },

    # --- INFRASTRUCTURE & CLOUD ---
    {
        "id": "devops_cloud",
        "title": "DevOps / Cloud Engineer",
        "skill_weights": {"Operating Systems": 0.30, "Computer Networks": 0.25, "DBMS": 0.10, "Python": 0.15, "Docker": 0.20},
        "personality_target": {"openness": 3, "conscientiousness": 4, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "sre",
        "title": "Site Reliability Engineer",
        "skill_weights": {"Python/Go": 0.20, "Networking": 0.20, "Monitoring": 0.30, "Incident Mgmt": 0.30},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 2, "agreeableness": 3, "neuroticism": 1},
    },
    {
        "id": "cloud_architect",
        "title": "Cloud Architect",
        "skill_weights": {"Cloud Design Patterns": 0.40, "Cost Optimization": 0.20, "Multi-cloud": 0.20, "Strategy": 0.20},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 4, "agreeableness": 3, "neuroticism": 1},
    },
    {
        "id": "db_admin",
        "title": "Database Administrator",
        "skill_weights": {"SQL Tuning": 0.40, "Backup/Recovery": 0.30, "Security": 0.15, "Cloud Databases": 0.15},
        "personality_target": {"openness": 2, "conscientiousness": 5, "extraversion": 2, "agreeableness": 3, "neuroticism": 3},
    },
    {
        "id": "network_engineer",
        "title": "Network Engineer",
        "skill_weights": {"TCP/IP": 0.40, "Routing/Switching": 0.30, "Firewalls": 0.20, "Automation": 0.10},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 3, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "linux_admin",
        "title": "Linux Systems Administrator",
        "skill_weights": {"Bash Scripting": 0.35, "Kernel Tuning": 0.25, "User Management": 0.20, "Security": 0.20},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 2, "agreeableness": 3, "neuroticism": 3},
    },
    {
        "id": "storage_engineer",
        "title": "Storage Engineer",
        "skill_weights": {"SAN/NAS": 0.40, "Data Retention": 0.25, "Hardware Arch": 0.20, "Networking": 0.15},
        "personality_target": {"openness": 2, "conscientiousness": 5, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "platform_engineer",
        "title": "Platform Engineer",
        "skill_weights": {"Kubernetes": 0.40, "Internal Tooling": 0.30, "DX": 0.15, "Cloud Native": 0.15},
        "personality_target": {"openness": 4, "conscientiousness": 4, "extraversion": 3, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "noc_engineer",
        "title": "NOC Engineer",
        "skill_weights": {"Monitoring": 0.40, "Ticketing": 0.20, "Alert Handling": 0.30, "Documentation": 0.10},
        "personality_target": {"openness": 2, "conscientiousness": 5, "extraversion": 3, "agreeableness": 4, "neuroticism": 4},
    },
    {
        "id": "virtualization_spec",
        "title": "Virtualization Specialist",
        "skill_weights": {"VMware/KVM": 0.45, "Hyper-V": 0.20, "Networking": 0.20, "Storage": 0.15},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },

    # --- GAME DEVELOPMENT ---
    {
        "id": "gameplay_programmer",
        "title": "Gameplay Programmer",
        "skill_weights": {"C++": 0.30, "Math/Physics": 0.25, "C# (Unity)": 0.25, "Game Design": 0.20},
        "personality_target": {"openness": 5, "conscientiousness": 3, "extraversion": 3, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "graphics_programmer",
        "title": "Graphics Programmer",
        "skill_weights": {"Shaders (GLSL/HLSL)": 0.40, "Linear Algebra": 0.30, "C++": 0.20, "Vulkan/DX12": 0.10},
        "personality_target": {"openness": 5, "conscientiousness": 5, "extraversion": 1, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "game_engine_eng",
        "title": "Game Engine Engineer",
        "skill_weights": {"C++": 0.45, "Memory Management": 0.25, "Multithreading": 0.20, "Tooling": 0.10},
        "personality_target": {"openness": 4, "conscientiousness": 5, "extraversion": 1, "agreeableness": 2, "neuroticism": 2},
    },
    {
        "id": "ar_vr_developer",
        "title": "AR/VR Developer",
        "skill_weights": {"C#": 0.30, "Unity/Unreal": 0.30, "3D Math": 0.20, "UX for Spatial": 0.20},
        "personality_target": {"openness": 5, "conscientiousness": 3, "extraversion": 3, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "technical_artist",
        "title": "Technical Artist",
        "skill_weights": {"Python": 0.25, "Maya/Blender API": 0.35, "Shaders": 0.20, "Visual Arts": 0.20},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 4, "agreeableness": 4, "neuroticism": 3},
    },
    {
        "id": "game_backend_eng",
        "title": "Game Backend Engineer",
        "skill_weights": {"Networking": 0.35, "DBMS": 0.25, "Go/Java": 0.25, "Scalability": 0.15},
        "personality_target": {"openness": 3, "conscientiousness": 4, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "game_designer",
        "title": "Game Designer",
        "skill_weights": {"Mechanics Design": 0.40, "Level Design": 0.30, "Scripting": 0.15, "Psychology": 0.15},
        "personality_target": {"openness": 5, "conscientiousness": 3, "extraversion": 4, "agreeableness": 4, "neuroticism": 3},
    },
    {
        "id": "ai_game_programmer",
        "title": "Game AI Programmer",
        "skill_weights": {"Pathfinding": 0.30, "Behavior Trees": 0.40, "C++": 0.20, "Math": 0.10},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "audio_programmer",
        "title": "Audio Programmer",
        "skill_weights": {"DSP": 0.45, "C++": 0.30, "Wwise/FMOD": 0.15, "Music Theory": 0.10},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 2, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "game_qa_tester",
        "title": "Game QA Tester",
        "skill_weights": {"Bug Reporting": 0.40, "Gaming Skill": 0.30, "Scripting": 0.10, "Persistence": 0.20},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 3, "agreeableness": 3, "neuroticism": 4},
    },

    # --- EMBEDDED & HARDWARE ---
    {
        "id": "embedded_eng",
        "title": "Embedded Systems Engineer",
        "skill_weights": {"C": 0.45, "Microcontrollers": 0.30, "RTOS": 0.15, "Electronics": 0.10},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "firmware_eng",
        "title": "Firmware Engineer",
        "skill_weights": {"C/Assembly": 0.45, "Hardware Debugging": 0.30, "Drivers": 0.15, "Compilers": 0.10},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 1, "agreeableness": 2, "neuroticism": 2},
    },
    {
        "id": "iot_architect",
        "title": "IoT Architect",
        "skill_weights": {"Wireless Protocols": 0.35, "Cloud Connectivity": 0.25, "C": 0.20, "Security": 0.20},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 3, "agreeableness": 3, "neuroticism": 1},
    },
    {
        "id": "fpga_engineer",
        "title": "FPGA Engineer",
        "skill_weights": {"Verilog/VHDL": 0.50, "Digital Logic": 0.30, "Signal Processing": 0.20},
        "personality_target": {"openness": 4, "conscientiousness": 5, "extraversion": 1, "agreeableness": 2, "neuroticism": 2},
    },
    {
        "id": "robotics_eng",
        "title": "Robotics Engineer",
        "skill_weights": {"ROS": 0.35, "C++": 0.25, "Control Systems": 0.25, "CAD": 0.15},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 3, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "automotive_sw_eng",
        "title": "Automotive Software Engineer",
        "skill_weights": {"AUTOSAR": 0.40, "C++": 0.30, "CAN Bus": 0.20, "Safety Standards": 0.10},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 3, "agreeableness": 3, "neuroticism": 1},
    },
    {
        "id": "chip_designer",
        "title": "IC Design Engineer",
        "skill_weights": {"VLSI": 0.45, "Analog Circuits": 0.30, "CAD Tools": 0.25},
        "personality_target": {"openness": 4, "conscientiousness": 5, "extraversion": 1, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "dsp_engineer",
        "title": "Signal Processing Engineer",
        "skill_weights": {"MATLAB": 0.40, "C": 0.25, "Math": 0.25, "Filter Design": 0.10},
        "personality_target": {"openness": 4, "conscientiousness": 5, "extraversion": 1, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "plc_programmer",
        "title": "PLC Programmer",
        "skill_weights": {"Ladder Logic": 0.45, "SCADA": 0.30, "Industrial Net": 0.25},
        "personality_target": {"openness": 2, "conscientiousness": 5, "extraversion": 3, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "embedded_linux_dev",
        "title": "Embedded Linux Developer",
        "skill_weights": {"Kernel Dev": 0.40, "Yocto": 0.30, "C": 0.20, "Shell": 0.10},
        "personality_target": {"openness": 4, "conscientiousness": 5, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },

    # --- MANAGEMENT & OPERATIONS ---
    {
        "id": "tech_pm",
        "title": "Technical Product Manager",
        "skill_weights": {"Agile": 0.30, "Market Analysis": 0.25, "Technical Strategy": 0.25, "Communication": 0.20},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 5, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "scrum_master",
        "title": "Scrum Master",
        "skill_weights": {"Facilitation": 0.40, "Conflict Mgmt": 0.30, "Agile Metrics": 0.20, "Jira": 0.10},
        "personality_target": {"openness": 3, "conscientiousness": 4, "extraversion": 5, "agreeableness": 5, "neuroticism": 2},
    },
    {
        "id": "eng_manager",
        "title": "Engineering Manager",
        "skill_weights": {"People Mgmt": 0.40, "System Design": 0.20, "Recruiting": 0.20, "Budgeting": 0.20},
        "personality_target": {"openness": 4, "conscientiousness": 5, "extraversion": 4, "agreeableness": 5, "neuroticism": 2},
    },
    {
        "id": "solutions_architect",
        "title": "Solutions Architect",
        "skill_weights": {"System Design": 0.40, "Presales": 0.20, "Cloud Services": 0.30, "Communication": 0.10},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 4, "agreeableness": 4, "neuroticism": 1},
    },
    {
        "id": "dev_advocate",
        "title": "Developer Advocate",
        "skill_weights": {"Public Speaking": 0.35, "Content Creation": 0.30, "Coding": 0.25, "Social Media": 0.10},
        "personality_target": {"openness": 5, "conscientiousness": 3, "extraversion": 5, "agreeableness": 5, "neuroticism": 3},
    },
    {
        "id": "it_director",
        "title": "IT Director",
        "skill_weights": {"Strategy": 0.40, "Budgeting": 0.30, "Governance": 0.20, "Leadership": 0.10},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 4, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "release_manager",
        "title": "Release Manager",
        "skill_weights": {"Coordination": 0.40, "CI/CD Pipelines": 0.30, "Risk Mgmt": 0.20, "Documentation": 0.10},
        "personality_target": {"openness": 2, "conscientiousness": 5, "extraversion": 4, "agreeableness": 4, "neuroticism": 3},
    },
    {
        "id": "it_support_mgr",
        "title": "IT Support Manager",
        "skill_weights": {"Service Desk Mgmt": 0.40, "SLA Compliance": 0.30, "Customer Service": 0.20, "Technical Training": 0.10},
        "personality_target": {"openness": 2, "conscientiousness": 5, "extraversion": 4, "agreeableness": 5, "neuroticism": 3},
    },
    {
        "id": "tech_recruiter",
        "title": "Technical Recruiter",
        "skill_weights": {"Sourcing": 0.40, "Tech Terms": 0.30, "Interviewing": 0.20, "Negotiation": 0.10},
        "personality_target": {"openness": 4, "conscientiousness": 4, "extraversion": 5, "agreeableness": 5, "neuroticism": 3},
    },
    {
        "id": "cto",
        "title": "Chief Technology Officer",
        "skill_weights": {"Innovation Strategy": 0.40, "Tech Evangelism": 0.30, "Architecture": 0.20, "Business Ops": 0.10},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 5, "agreeableness": 3, "neuroticism": 2},
    },

    # --- QUALITY & TESTING ---
    {
        "id": "automation_qa",
        "title": "QA Automation Engineer",
        "skill_weights": {"Selenium/Playwright": 0.40, "Python/JS": 0.25, "Test Planning": 0.20, "CI/CD": 0.15},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 3, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "sdet",
        "title": "SDET (Software Dev in Test)",
        "skill_weights": {"Coding": 0.40, "System Architecture": 0.20, "Testing Frameworks": 0.30, "DevOps": 0.10},
        "personality_target": {"openness": 4, "conscientiousness": 5, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "manual_tester",
        "title": "Manual QA Tester",
        "skill_weights": {"User Perspective": 0.40, "Bug Reporting": 0.30, "Attention to Detail": 0.30},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 3, "agreeableness": 4, "neuroticism": 3},
    },
    {
        "id": "perf_tester",
        "title": "Performance Engineer",
        "skill_weights": {"JMeter/K6": 0.45, "Analysis": 0.25, "System Internals": 0.20, "Reporting": 0.10},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "security_tester",
        "title": "Security QA",
        "skill_weights": {"Vulnerability Scanning": 0.40, "DAST/SAST": 0.35, "Remediation Guidance": 0.25},
        "personality_target": {"openness": 4, "conscientiousness": 5, "extraversion": 2, "agreeableness": 3, "neuroticism": 3},
    },

    # --- NICHE & SPECIALIZED ---
    {
        "id": "blockchain_dev",
        "title": "Blockchain Developer",
        "skill_weights": {"Solidity": 0.40, "Cryptography": 0.30, "Web3.js": 0.15, "P2P Networking": 0.15},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 3, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "smart_contract_auditor",
        "title": "Smart Contract Auditor",
        "skill_weights": {"Vulnerability Research": 0.45, "EVM Internals": 0.35, "Solidity": 0.20},
        "personality_target": {"openness": 5, "conscientiousness": 5, "extraversion": 2, "agreeableness": 2, "neuroticism": 3},
    },
    {
        "id": "bioinformatics_dev",
        "title": "Bioinformatics Developer",
        "skill_weights": {"Python": 0.30, "Statistics": 0.30, "Genomics": 0.40},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 1, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "gis_developer",
        "title": "GIS Developer",
        "skill_weights": {"Spatial Data": 0.40, "Javascript (Leaflet)": 0.25, "Python": 0.25, "Geometry": 0.10},
        "personality_target": {"openness": 4, "conscientiousness": 4, "extraversion": 3, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "quantum_sw_eng",
        "title": "Quantum Software Engineer",
        "skill_weights": {"Qiskit": 0.40, "Quantum Physics": 0.40, "Python": 0.20},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 1, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "salesforce_dev",
        "title": "Salesforce Developer",
        "skill_weights": {"Apex": 0.40, "Lightning Components": 0.30, "CRM Logic": 0.30},
        "personality_target": {"openness": 2, "conscientiousness": 4, "extraversion": 4, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "sap_consultant",
        "title": "SAP Consultant",
        "skill_weights": {"ABAP": 0.40, "Business Process": 0.40, "SQL": 0.20},
        "personality_target": {"openness": 2, "conscientiousness": 5, "extraversion": 4, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "shopify_dev",
        "title": "Shopify/E-commerce Dev",
        "skill_weights": {"Liquid": 0.40, "Javascript": 0.30, "CSS": 0.20, "Marketing APIs": 0.10},
        "personality_target": {"openness": 4, "conscientiousness": 3, "extraversion": 4, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "rpa_developer",
        "title": "RPA Developer (UiPath)",
        "skill_weights": {"Process Mapping": 0.40, "UiPath/BluePrism": 0.40, "VB.NET/C#": 0.20},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 3, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "tech_writer",
        "title": "Technical Writer",
        "skill_weights": {"Writing": 0.50, "Markdown": 0.20, "Coding Basics": 0.20, "API Documentation": 0.10},
        "personality_target": {"openness": 4, "conscientiousness": 5, "extraversion": 2, "agreeableness": 5, "neuroticism": 2},
    },
    {
        "id": "ux_researcher",
        "title": "UX Researcher",
        "skill_weights": {"Interviewing": 0.40, "User Psychology": 0.30, "Data Synthesis": 0.20, "Prototyping": 0.10},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 4, "agreeableness": 5, "neuroticism": 2},
    },
    {
        "id": "accessibility_spec",
        "title": "Accessibility Specialist",
        "skill_weights": {"WCAG Standards": 0.45, "HTML/CSS": 0.25, "Assistive Tech": 0.30},
        "personality_target": {"openness": 4, "conscientiousness": 5, "extraversion": 3, "agreeableness": 5, "neuroticism": 2},
    },
    {
        "id": "seo_engineer",
        "title": "SEO Engineer",
        "skill_weights": {"Web Performance": 0.35, "HTML Semantics": 0.35, "Analytics": 0.20, "Search Algorithms": 0.10},
        "personality_target": {"openness": 4, "conscientiousness": 4, "extraversion": 3, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "reliability_eng",
        "title": "Reliability Engineer",
        "skill_weights": {"Probability": 0.35, "Failure Analysis": 0.35, "Testing": 0.20, "Reporting": 0.10},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 2, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "data_privacy_officer",
        "title": "Data Privacy Officer",
        "skill_weights": {"GDPR/CCPA": 0.50, "Risk Management": 0.30, "Technical Audit": 0.20},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 3, "agreeableness": 4, "neuroticism": 3},
    },
    {
        "id": "fintech_dev",
        "title": "Fintech Engineer",
        "skill_weights": {"Secure Transactions": 0.40, "Java/C#": 0.30, "Compliance": 0.20, "SQL": 0.10},
        "personality_target": {"openness": 3, "conscientiousness": 5, "extraversion": 3, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "edtech_dev",
        "title": "EdTech Developer",
        "skill_weights": {"LMS Integration": 0.35, "Javascript": 0.30, "Pedagogical UX": 0.25, "Python": 0.10},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 3, "agreeableness": 5, "neuroticism": 2},
    },
    {
        "id": "medtech_sw_eng",
        "title": "Medical Software Engineer",
        "skill_weights": {"HIPAA/Regulatory": 0.40, "C++": 0.30, "Reliability": 0.20, "Imaging APIs": 0.10},
        "personality_target": {"openness": 4, "conscientiousness": 5, "extraversion": 2, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "greentech_dev",
        "title": "GreenTech Software Engineer",
        "skill_weights": {"Energy Data Analysis": 0.35, "Python": 0.30, "IoT APIs": 0.25, "Carbon Modeling": 0.10},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 3, "agreeableness": 5, "neuroticism": 2},
    },
    {
        "id": "agritech_dev",
        "title": "AgriTech Developer",
        "skill_weights": {"GIS": 0.30, "IoT": 0.30, "Python": 0.25, "Remote Sensing": 0.15},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 3, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "voice_ui_dev",
        "title": "Voice UI Developer (Alexa/Siri)",
        "skill_weights": {"VUI Design": 0.40, "NLP Basics": 0.30, "Node.js": 0.20, "SSML": 0.10},
        "personality_target": {"openness": 5, "conscientiousness": 3, "extraversion": 4, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "desktop_app_dev",
        "title": "Desktop App Developer",
        "skill_weights": {"C#/.NET": 0.40, "Electron": 0.20, "OS Integration": 0.25, "UI Design": 0.15},
        "personality_target": {"openness": 3, "conscientiousness": 4, "extraversion": 2, "agreeableness": 4, "neuroticism": 2},
    },
    {
        "id": "compiler_eng",
        "title": "Compiler Engineer",
        "skill_weights": {"LLVM/GCC": 0.45, "C++": 0.30, "Automata Theory": 0.25},
        "personality_target": {"openness": 4, "conscientiousness": 5, "extraversion": 1, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "perf_tuning_specialist",
        "title": "Performance Tuning Specialist",
        "skill_weights": {"Profiling Tools": 0.40, "C/C++": 0.30, "Assembly": 0.20, "Math": 0.10},
        "personality_target": {"openness": 4, "conscientiousness": 5, "extraversion": 1, "agreeableness": 3, "neuroticism": 2},
    },
    {
        "id": "dev_experience_eng",
        "title": "Developer Experience (DX) Engineer",
        "skill_weights": {"Tooling": 0.40, "API Design": 0.30, "Documentation": 0.15, "Community Engagement": 0.15},
        "personality_target": {"openness": 5, "conscientiousness": 4, "extraversion": 4, "agreeableness": 5, "neuroticism": 2},
    },
]